### ISSUE TITLE
Creating release fails

### ISSUE THREAD

**Issue by Jandev** [Jandev/azurefunctions-eventgrid#17]
The creation of a release looks like this.
```yml
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        prerelease: true
```
On consecutive builds, this fails.

The Action should be reworked to use GitVersion.
